hercules-ci/flake.parts-website

flake.lock
flake.nix
render/render-module.nix
site/src/SUMMARY.md

To actually show options, needs
- https://github.com/Platonic-Systems/mission-control/pull/11

Add mission control

---

flake.lock
flake.nix
site/src/SUMMARY.md

Preview: https://63a72d0d68ae8914a7a364d7--sprightly-cassata-33312f.netlify.app/options/treefmt-nix.html

Add treefmt-nix

---

flake.lock
flake.nix
site/src/SUMMARY.md

Preview link: https://63a4d4bf550e7b25bfc7354e--sprightly-cassata-33312f.netlify.app/options/process-compose-flake.html
Depends on https://github.com/Platonic-Systems/process-compose-flake/pull/3
and then cleanup

Add process compose flake

---

dev-module.nix
flake.lock
site/site-module.nix

Blocked on https://github.com/NixOS/nixpkgs/pull/212633

Add linkchecker for anchors

---

flake.lock
flake.nix
site/src/SUMMARY.md

Adds nix-cargo-integration flake-parts module.

feat: add nix-cargo-integration

---

flake.lock
flake.nix
site/src/SUMMARY.md

[I recommend squash merging; unclean commit history!]
<details>
Getting a strange error:
```
❯ nix build
warning: input 'mission-control' has an override for a non-existent input 'nixpkgs'
error: Couldn't figure out flakeref for emanote: https://github.com/srid/emanote
(use '--show-trace' to show detailed location information)
```
</details>

Add emanote module

---

flake.nix

Improve devenv description

---

render/render-module.nix

Add self.outPath to explain why its not available

---

flake.lock

Still figuring out some things. Blocked on:
- https://github.com/nix-community/dream2nix/issues/596
- https://github.com/nix-community/dream2nix/pull/597

Dream2nix v1

---

flake.lock
flake.nix

Updates nix-cargo-integration input and fixes the module name for it.

fix: update nci input and fix module name

---

dev-module.nix
flake.lock
site/site-module.nix
site/src/overlays.md

Use lychee for link check

---

flake.lock
flake.nix

This adds documentation for the [agenix-rekey](https://github.com/oddlama/agenix-rekey) flake-parts module.

Add agenix-rekey

---

flake.lock
flake.nix

This adds documentation for the [nix-topology](https://github.com/oddlama/nix-topology) flake-parts module.

Add nix-topology

---

flake.nix

I realized that markdown is fully possible. This PR adds an example to make it more user friendly.

Extend mkdocs-flake intro text

---

flake.lock
flake.nix

New module: https://github.com/drupol/pkgs-by-name-for-flake-parts

module/pkgs-by-name-for-flake-parts: init

---

flake.lock
flake.nix

Might speed up eval, maybe avoid some merge conflicts when contributors apply also do this.
Wouldn't be needed if it wasn't for a lack of https://github.com/NixOS/nix/issues/7730.

Prune some Nixpkgs

---

flake.lock
flake.nix
render/render-module.nix

I consider https://github.com/juspay/rust-flake ready for basic use.

Add `rust-flake`

---

site/book.toml
site/flake-parts.css
site/site-module.nix

Bring back the table of contents

Add mdbook-pagetoc

---

flake.lock
flake.nix

Currently depends on https://github.com/terranix/terranix/pull/111

Add `terranix`

---

flake.lock
flake.nix

https://github.com/terranix/terranix/pull/111 has been merged 🎉

Point terranix to main

---

flake.lock
flake.nix

feat: easy-hosts

---

flake.lock
flake.nix
render/render-module.nix

Hi @9glenda, I'd be happy to un-archive it if it is maintained in a new location.
I'll have to move forward with this first, to unblock publishing.

Archive ocaml-flake

---

flake.lock
flake.nix

because the repository does not exist anymore:
https://github.com/9glenda/ocaml-flake => 404
```
error: Failed to open archive (Source threw exception: error: unable to download 'https://github.com/9glenda/ocaml-flake/archive/82d25b5805323fa13d7b4350a7fe68d2b59a82e6.tar.gz': HTTP error 404
```

Remove ocaml-flake

---

flake.lock
flake.nix

Is based on https://github.com/hercules-ci/flake.parts-website/pull/1329 otherwise I couldn't build it.

Add nixos-healthchecks

---

flake.lock
flake.nix

Adds documentation for my module which is used for generation of GitHub/Gitea action `yaml` files using `nix`.

Add actions.nix

---

README.md
dev-module.nix
site/flake-parts.css
site/no-edit-options.js
site/src/SUMMARY.md
site/src/best-practices-for-module-writing.md
site/src/cheat-sheet.md
site/src/debug.md
site/src/define-custom-flake-attribute.md
site/src/define-module-in-separate-file.md
site/src/dogfood-a-reusable-module.md
site/src/getting-started.md
site/src/module-arguments.md
site/src/overlays.md
site/src/system.md

To ease review, separated into atomic commits.

Set up `nix fmt` and force formatting of all files

---

site/src/define-module-in-separate-file.md

Fixes https://github.com/hercules-ci/flake-parts/issues/306

fix `importApply` example
